# Generated by Django 5.0.4 on 2024-05-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_cart_cartitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
